Release `v0.0.3-b` Exit GH actions if release ID is null

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -76,6 +76,10 @@ jobs:
             "https://api.github.com/repos/${{ github.repository }}/releases")
 
           release_id=$(echo $response | jq -r .id)
+          if [ -z "$release_id" ]; then
+            echo "Error: release_id is null. Exiting with code 1."
+            exit 1
+          fi
           echo "Release ID: $release_id"
           echo "release_id=$release_id" >> "$GITHUB_OUTPUT"
         shell: bash
